[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hai817i_ml"
version = "0.1.0"
description = "Projet Machine Learning - Méthodes classiques"
dependencies = [
    "contractions",
    "emoji",
    "imbalanced-learn",
    "joblib",
    "matplotlib",
    "numpy",
    "optuna",
    "pandas",
    "plotly",
    "scikit-learn",
    "seaborn",
    "spacy",
    "sqlalchemy",
    "wordcloud"
]

[tool.setuptools]
# On indique explicitement à setuptools de ne chercher aucun package Python à compiler
packages = []